### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by groundwater** [groundwater/learn-linkers#2]
- [ ] separate `Makefile`s for each build style
  - [ ] direct-object builds
  - [ ] archive-file builds
  - [ ] shared object builds
- [ ] rename project to `C++ Primer` to include more aspects
- [ ] introduce disable copy macros
- [ ] introduce stack-allocated resource management
  - [ ] smart pointers
